(function(m,z,t){if("object"===typeof t&&"string"!==typeof t.nodeName)z(m,t);else{var x=function(c){for(var k in c)c.hasOwnProperty(k)&&(c[k]=x(c[k]));return Object.freeze(c)};t={};z(m,t);for(var q in t)!t.hasOwnProperty(q)||null!=Object.getOwnPropertyDescriptor(m,q)&&null!=Object.getOwnPropertyDescriptor(m[q],"1.2.6-iab634")||(null==Object.getOwnPropertyDescriptor(m,q)&&Object.defineProperty(m,q,{value:{}}),Object.defineProperty(m[q],"1.2.6-iab634",{get:function(){return x(t[q])},enumerable:!0}))}})("undefined"===
typeof global?this:global,function(m,z){function t(a,b){return a&&(a[b]||(a[b]={}))}function x(a,b){"undefined"!==typeof jasmine&&jasmine?a():"undefined"!==typeof console&&console&&console.error&&b()}function q(a,b){return b.reduce(function(a,b){return a&&a[b]},a)}var c=c||{};c.scope={};c.inherits=function(a,b){function d(){}d.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new d;a.prototype.constructor=a;for(var c in b)if("prototype"!=c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,
c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c]};c.ASSUME_ES5=!1;c.ASSUME_NO_NATIVE_MAP=!1;c.ASSUME_NO_NATIVE_SET=!1;c.defineProperty=c.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};c.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};c.global=c.getGlobal(this);c.SYMBOL_PREFIX="jscomp_symbol_";c.initSymbol=function(){c.initSymbol=
function(){};c.global.Symbol||(c.global.Symbol=c.Symbol)};c.symbolCounter_=0;c.Symbol=function(a){return c.SYMBOL_PREFIX+(a||"")+c.symbolCounter_++};c.initSymbolIterator=function(){c.initSymbol();var a=c.global.Symbol.iterator;a||(a=c.global.Symbol.iterator=c.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&c.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return c.arrayIterator(this)}});c.initSymbolIterator=function(){}};c.arrayIterator=function(a){var b=
0;return c.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};c.iteratorPrototype=function(a){c.initSymbolIterator();a={next:a};a[c.global.Symbol.iterator]=function(){return this};return a};c.makeIterator=function(a){c.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):c.arrayIterator(a)};c.arrayFromIterator=function(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d};c.arrayFromIterable=function(a){return a instanceof Array?a:c.arrayFromIterator(c.makeIterator(a))};
var k={assertTruthyString:function(a,b){if(!b)throw Error("Value for "+a+" is undefined, null or blank.");if("string"!==typeof b&&!(b instanceof String))throw Error("Value for "+a+" is not a string.");if(""===b.trim())throw Error("Value for "+a+" is empty string.");},assertNotNullObject:function(a,b){if(null==b)throw Error("Value for "+a+" is undefined or null");},assertNumber:function(a,b){if(null==b)throw Error(a+" must not be null or undefined.");if("number"!==typeof b||isNaN(b))throw Error("Value for "+
a+" is not a number");},assertNumberBetween:function(a,b,d,c){(0,k.assertNumber)(a,b);if(b<d||b>c)throw Error("Value for "+a+" is outside the range ["+d+","+c+"]");},assertFunction:function(a,b){if(!b)throw Error(a+" must not be truthy.");},assertPositiveNumber:function(a,b){(0,k.assertNumber)(a,b);if(0>b)throw Error(a+" must be a positive number.");}};var D=function(a){return/\d+\.\d+\.\d+(-.*)?/.test(a)};var E=function(a,b){a=a.split("-")[0].split(".");b=b.split("-")[0].split(".");for(var d=0;3>
d;d++){var c=parseInt(a[d],10),e=parseInt(b[d],10);if(c>e)break;else if(c<e)return!1}return!0};var G=function(a,b){return(0,D)(a)&&(0,E)(a,"1.0.3")?b:JSON.stringify(b)};var w=function(a,b){return(0,D)(a)&&(0,E)(a,"1.0.3")?b?b:[]:b&&"string"===typeof b?JSON.parse(b):[]};var r=function(a,b,d,c){this.guid=a;this.method=b;this.version=d;this.args=c};r.isValidSerializedMessage=function(a){return!!a&&void 0!==a.omid_message_guid&&void 0!==a.omid_message_method&&void 0!==a.omid_message_version&&"string"===
typeof a.omid_message_guid&&"string"===typeof a.omid_message_method&&"string"===typeof a.omid_message_version&&(void 0===a.omid_message_args||void 0!==a.omid_message_args)};r.deserialize=function(a){return new r(a.omid_message_guid,a.omid_message_method,a.omid_message_version,a.omid_message_args)};r.prototype.serialize=function(){var a={};a=(a.omid_message_guid=this.guid,a.omid_message_method=this.method,a.omid_message_version=this.version,a);void 0!==this.args&&(a.omid_message_args=this.args);return a};
var u=function(a){this.to=a;this.communicationType_="NONE"};u.prototype.sendMessage=function(a,b){};u.prototype.handleMessage=function(a,b){if(this.onMessage)this.onMessage(a,b)};u.prototype.generateGuid=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return a="y"===a?(b&3|8).toString(16):b.toString(16)})};u.prototype.serialize=function(a){return JSON.stringify(a)};u.prototype.deserialize=function(a){return JSON.parse(a)};u.prototype.isDirectCommunication=
function(){return"DIRECT"===this.communicationType_};var l={OMID_PRESENT_FRAME_NAME:"omid_v1_present",isOmidPresent:function(a){try{return a.frames?!!a.frames[l.OMID_PRESENT_FRAME_NAME]:!1}catch(b){return!1}},declareOmidPresence:function(a){a.frames&&a.document&&(l.OMID_PRESENT_FRAME_NAME in a.frames||(null==a.document.body&&l.isMutationObserverAvailable_(a)?l.registerMutationObserver_(a):a.document.body?l.appendPresenceIframe_(a):a.document.write('<iframe style="display:none" '+('id="'+l.OMID_PRESENT_FRAME_NAME+
'"')+(' name="'+l.OMID_PRESENT_FRAME_NAME+'">')+"</iframe>")))},appendPresenceIframe_:function(a){var b=a.document.createElement("iframe");b.id=l.OMID_PRESENT_FRAME_NAME;b.name=l.OMID_PRESENT_FRAME_NAME;b.style.display="none";a.document.body.appendChild(b)},isMutationObserverAvailable_:function(a){return"MutationObserver"in a},registerMutationObserver_:function(a){var b=new MutationObserver(function(c){c.forEach(function(c){"BODY"===c.addedNodes[0].nodeName&&(l.appendPresenceIframe_(a),b.disconnect())})});
b.observe(a.document.documentElement,{childList:!0})}},p=function(a){u.call(this,a);this.communicationType_="DIRECT";this.handleExportedMessage=p.prototype.handleExportedMessage.bind(this)};c.inherits(p,u);p.prototype.sendMessage=function(a,b){b=void 0===b?this.to:b;if(!b)throw Error("Message destination must be defined at construction time or when sending the message.");b.handleExportedMessage(a.serialize(),this)};p.prototype.handleExportedMessage=function(a,b){r.isValidSerializedMessage(a)&&this.handleMessage(r.deserialize(a),
b)};var v={error:function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];x(function(){throw new (Function.prototype.bind.apply(Error,[null].concat(["Could not complete the test successfully - "],c.arrayFromIterable(b))));},function(){return console.error.apply(console,[].concat(c.arrayFromIterable(b)))})},debug:function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];x(function(){},function(){return console.error.apply(console,[].concat(c.arrayFromIterable(b)))})}},
A=eval("this");var g=function(){if("undefined"!==typeof m&&m)return m;if("undefined"!==typeof global&&global)return global;if("undefined"!==typeof window&&window)return window;if("undefined"!==typeof A&&A)return A;throw Error("Could not determine global object context.");}();var n=function(a,b){b=void 0===b?g:b;u.call(this,b);var c=this;this.communicationType_="POST_MESSAGE";a.addEventListener("message",function(a){if("object"===typeof a.data){var b=a.data;r.isValidSerializedMessage(b)&&(b=r.deserialize(b),
a.source&&c.handleMessage(b,a.source))}})};c.inherits(n,u);n.isCompatibleContext=function(a){return!!(a&&a.addEventListener&&a.postMessage)};n.prototype.sendMessage=function(a,b){b=void 0===b?this.to:b;if(!b)throw Error("Message destination must be defined at construction time or when sending the message.");b.postMessage(a.serialize(),"*")};var H=function(a){"undefined"===typeof a&&"undefined"!==typeof window&&window&&(a=window);if("undefined"===typeof a||!a||"undefined"===typeof a.top||!a.top)return g;
if(a===a.top)return a;try{return"undefined"===typeof a.top.location.hostname?a:a.top}catch(b){return a}};var F=function(a,b,c){c=void 0===c?l.isOmidPresent:c;return(b=q(a,b))?new p(b):a.top&&c(a.top)?new n(a,a.top):null};var h=function(a){if(this.communication=void 0===a?(0,F)((0,H)(),["omid","v1_VerificationServiceCommunication"]):a)this.communication.onMessage=this.handleMessage_.bind(this);else if(a=(a=g.omid3p)&&"function"===typeof a.registerSessionObserver&&"function"===typeof a.addEventListener?
a:null)this.omid3p=a;this.remoteIntervals_=this.remoteTimeouts_=0;this.callbackMap_={};this.imgCache_=[]};h.prototype.isSupported=function(){return!!this.communication};h.prototype.registerSessionObserver=function(a,b){(0,k.assertFunction)("functionToExecute",a);this.omid3p?this.omid3p.registerSessionObserver(a,b):this.sendMessage_("addSessionListener",a,b)};h.prototype.addEventListener=function(a,b){(0,k.assertTruthyString)("eventType",a);(0,k.assertFunction)("functionToExecute",b);this.omid3p?this.omid3p.addEventListener(a,
b):this.sendMessage_("addEventListener",b,a)};h.prototype.sendUrl=function(a,b,c){(0,k.assertTruthyString)("url",a);g.document&&g.document.createElement?this.sendUrlWithImg_(a,b,c):this.sendMessage_("sendUrl",function(a){a&&b?b():!a&&c&&c()},a)};h.prototype.sendUrlWithImg_=function(a,b,c){var d=this,e=g.document.createElement("img");this.imgCache_.push(e);var f=function(a){var b=d.imgCache_.indexOf(e);0<=b&&d.imgCache_.splice(b,1);a&&a()};e.addEventListener("load",f.bind(this,b));e.addEventListener("error",
f.bind(this,c));e.src=a};h.prototype.injectJavaScriptResource=function(a,b,c){var d=this;(0,k.assertTruthyString)("url",a);g.document?this.injectJavascriptResourceUrlInDom_(a,b,c):this.sendMessage_("injectJavaScriptResource",function(e,f){e?(d.evaluateJavaScript_(f,a),b()):(v.error("Service failed to load JavaScript resource."),c())},a)};h.prototype.injectJavascriptResourceUrlInDom_=function(a,b,c){var d=g.document,e=d.body;d=d.createElement("script");d.onload=b;d.onerror=c;d.src=a;d.type="application/javascript";
e.appendChild(d)};h.prototype.evaluateJavaScript_=function(a,b){try{eval(a)}catch(d){v.error('Error evaluating the JavaScript resource from "'+b+'".')}};h.prototype.setTimeout=function(a,b){(0,k.assertFunction)("functionToExecute",a);(0,k.assertPositiveNumber)("timeInMillis",b);if(this.hasTimeoutMethods_())return g.setTimeout(a,b);var c=this.remoteTimeouts_++;this.sendMessage_("setTimeout",a,c,b);return c};h.prototype.clearTimeout=function(a){(0,k.assertPositiveNumber)("timeoutId",a);this.hasTimeoutMethods_()?
g.clearTimeout(a):this.sendOneWayMessage_("clearTimeout",a)};h.prototype.setInterval=function(a,b){(0,k.assertFunction)("functionToExecute",a);(0,k.assertPositiveNumber)("timeInMillis",b);if(this.hasIntervalMethods_())return g.setInterval(a,b);var c=this.remoteIntervals_++;this.sendMessage_("setInterval",a,c,b);return c};h.prototype.clearInterval=function(a){(0,k.assertPositiveNumber)("intervalId",a);this.hasIntervalMethods_()?g.clearInterval(a):this.sendOneWayMessage_("clearInterval",a)};h.prototype.hasTimeoutMethods_=
function(){return"function"===typeof g.setTimeout&&"function"===typeof g.clearTimeout};h.prototype.hasIntervalMethods_=function(){return"function"===typeof g.setInterval&&"function"===typeof g.clearInterval};h.prototype.handleMessage_=function(a,b){b=a.method;var c=a.guid;a=a.args;if("response"===b&&this.callbackMap_[c]){var g=(0,w)("1.2.6-iab634",a);this.callbackMap_[c].apply(this,g)}"error"===b&&window.console&&v.error(a)};h.prototype.sendOneWayMessage_=function(a,b){for(var d=[],g=1;g<arguments.length;++g)d[g-
1]=arguments[g];this.sendMessage_.apply(this,[].concat([a,null],c.arrayFromIterable(d)))};h.prototype.sendMessage_=function(a,b,c){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];this.communication&&(e=this.communication.generateGuid(),b&&(this.callbackMap_[e]=b),d=new r(e,"VerificationService."+a,"1.2.6-iab634",(0,G)("1.2.6-iab634",d)),this.communication.sendMessage(d))};(0,function(a,b,c){if(c=void 0===c?"undefined"===typeof z?null:z:c)a=a.split("."),a.slice(0,a.length-1).reduce(t,c)[a[a.length-
1]]=b})("OmidVerificationClient",h)},"undefined"===typeof exports?void 0:exports);
(function(){function m(){var a=(new Date).getTime(),b=1;if(A)for(var c=Math.floor(10*Math.random())+1,d=0;d<c;++d)b*=Math.random();else b=(new Date).getSeconds();return a*b}function z(){var a={location:{protocol:"https:"}};a.parent=a;a.top=a;a.document={getElementById:function(){},createElement:function(){},body:{insertBefore:function(){}},querySelectorAll:function(){return[]}};return a}function t(a,b){var f=e.getReportUrl(e.ErrorTypes.LoadTagError,"failedToLoadDVM",!0),B="window.tagUniqueKey = '"+
g+"'",d=c(a);b='<html><head><script type="text/javascript">'+B+';\x3c/script><script type="text/javascript">('+function(){window.$dv=window.parent.$dv;window.$dv.isFrameSupported=!0;window.$frmId=Math.random().toString(36)+Math.random().toString(36);window.dv_flow=2}.toString()+')();\x3c/script></head><body><script type="text/javascript">('+function(a,b){if(a){var c=document.createElement("script");c.src=a;c.onerror=function(){(new Image(1,1)).src=b};document.body.appendChild(c)}}.toString()+')("'+
b+'", "'+f+'");\x3c/script></body></html>';d?(d.open(),d.write(b),d.close()):(d=encodeURIComponent(b.replace(/'/g,"\\'").replace(/\n|\r\n|\r/g,"")),a.src='javascript: (function(){document.open();document.domain="'+window.document.domain+"\";document.write('"+d+"');})()")}function x(a){var b=Math.floor(1E12*(Math.random()+"")),c=document.createElement("iframe");c.name=c.id="iframe_"+b;c.setAttribute("data-dv-frm",b);c.width="0";c.height="0";c.style.display="none";c.src=a;return c}function q(a){if(document.currentScript){var b=
document.currentScript.parentNode;b&&"function"===typeof b.insertBefore?b.insertBefore(a,document.currentScript):document.currentScript.appendChild(a)}else document.body&&"function"===typeof document.body.insertBefore?document.body.firstChild?document.body.insertBefore(a,document.body.firstChild):document.body.appendChild(a):(b=document.getElementsByTagName("head")[0])&&"function"===typeof document.body.insertBefore&&b.firstChild?b.insertBefore(a,b.firstChild):document.documentElement.appendChild(a)}
function c(a){return a&&(a.contentDocument||a.contentWindow&&a.contentWindow.document||frames&&frames[a.name]&&frames[a.name].document)}function k(a){if(p)return E(a);var b=x("about:blank");q(b);t(b,a)}function D(a){try{(new Image(1,1)).src=a}catch(B){}}function E(a,b,c){var f=document.createElement("script");f.onload=b||l;f.onerror=c||l;f.src=a;f.type="application/javascript";q(f);$dv.tagData[g].isSibling=1}function G(a,b,c){b=b||l;c=c||l;if(n){var f=e.ErrorTypes.OmidLoadTagError;if("object"===typeof omidNative&&
"function"===typeof omidNative.downloadJavaScriptResource)omidNative.downloadJavaScriptResource(a,function(a){try{eval(a),b()}catch(y){c(y),d=e.getReportUrl(f,"FailedToEval__"+y.message,!0),w(d)}},function(){d=e.getReportUrl(f,"FailedToDownload",!0);w(d)});else{var d=e.getReportUrl(f,"omidNativeNotFound",!0);w(d)}}else E(a,b,c)}function w(a,b,c){b=b||l;c=c||l;if(n){if("object"===typeof omidNative&&"function"===typeof omidNative.sendUrl)return omidNative.sendUrl(a,b,c)}else{var f=new Image(1,1);f.onerror=
c;f.onload=b;f.src=a}}function r(b,c,d){b||(b={message:"error undefined"});c=["https://tps.doubleverify.com/visit.jpg?ctx=818052&cmp=1619415&dvtagver=6.1.src&dvp_isLostImp=",d,"&napr=",b.message,"&cerrt=",c,"&tgjsver=731"].join("");n&&(c+="&dvp_idle=1");p&&(c+="&dvp_csp=1&dvp_csplog="+v);(b=a&&a.isSupported())&&(c+="&dvp_iomd=1");A||(c+="&dvp_imrns=1");c=encodeURI(c);b?a.report(c):D(c)}function u(a,b,c,d,e,g){a.tagData||(a.tagData={});for(var f=a.tagData,J=5;f[b]&&--J;)b=m();if(f[b])throw Error("failed to create tagUniqueKey");
a.tagData[b]={};a.tagData[b].dvtpScriptVersion=c;a.tagData[b].dvtpScriptUrl=d;a.tagData[b].cspIndicatorLogger=v;a.tagData[b].restrictedAccess=e;a.tagData[b].$frmId=g;a.tagData[b].tagScriptElem=F;a.tagData[b].tagLoadedMS=(new Date).getTime()}var l=function(){};dv_flow=2;var p=!1,v=0,A="object"===typeof Math&&"function"===typeof Math.random&&!isNaN(Math.random())&&0<=Math.random()&&1>=Math.random();try{var g=m()}catch(f){g=0}var n="undefined"===typeof window,H=!(n||!document.currentScript),F=function(){try{if(!n&&
document){if(H){var a=document.currentScript;a.dvvisit=1;return a}if("function"===typeof document.getElementsByTagName)for(var b=document.getElementsByTagName("script"),c=0,d=b.length,e=!1;c<d;++c)if((a=b[c])&&!a.dvvisit&&a.src&&-1!==a.src.indexOf("//cdn.doubleverify.com/dvtp_src.js")){a.dvvisit=1;e=!0;break}if(!e)throw Error("dvtp script element did not find");return a}}catch(K){r(K,19,!1)}}();if(!n)try{(function(){try{try{var a=x("about:blank")}catch(B){v|=64;return}try{q(a)}catch(B){v|=1;return}p=
!c(a)}catch(B){p=!0,v|=2}a&&"function"===typeof a.remove&&a.remove()})()}catch(f){}var h=function(){var a;return{getMeasurementsScriptUrl:function(b){if(!a){var c=[{src:"dv-measurements"}];a=c&&c[0]}return a&&[b,"//cdn.doubleverify.com/",a.src,"731.js"].join("")}}}(),a={omidObject:null,isOmidSupported:null,report:w,isSupported:function(){if(null!==this.isOmidSupported&&void 0!==this.isOmidSupported)return this.isOmidSupported;try{this.omidObject||(this.omidObject=new OmidVerificationClient["1.2.6-iab634"]),
this.isOmidSupported=this.omidObject.isSupported()}catch(B){if(this.isOmidSupported=!1,e){var a=e.getReportUrl(e.ErrorTypes.OmidUnexpectedError,"isSupported__"+B.message,!1);this.report(a)}}return this.isOmidSupported},getVendorKey:function(){if(!n&&C){var a=(a=C.getQueryStringParams())&&a.vendor_key;window.$dv.omidVendorKeyExtracted=Number(!!a)}return a||"doubleverify.com-omid"},execute:function(){var a=this,b=this.omidObject,c=this.getVendorKey();$dv.omidJsClient=b;$dv.omidVendorKey=c;($dv.isDomlessEnvironment=
n)&&(window=z());b.registerSessionObserver(function(b){try{switch(b.type){case "sessionStart":$dv.omidSessionData=b;$dv.omidAccessMode=b&&b.data&&b.data.context&&b.data.context.accessMode;try{$dv.omidSessionStartTime=Date.now?Date.now():(new Date).getTime()}catch(y){var c=e.getReportUrl(e.ErrorTypes.OmidUnexpectedError,"Date.now__"+y.message,!1);w(c)}var d=h.getMeasurementsScriptUrl("https:");if(n)G(d);else try{k(d)}catch(y){v|=128,c=e.getReportUrl(e.ErrorTypes.OmidUnexpectedError,"injectScriptSteps__"+
y.message,!1),w(c),window.tagUniqueKey=g,G(d)}break;case "sessionError":c=e.getReportUrl(e.ErrorTypes.OmidSessionError,b.data&&b.data.message||"",!0),a.report(c)}}catch(y){b=e.getReportUrl(e.ErrorTypes.OmidUnexpectedLostImpError,"omidCallback__"+y.message,!0),w(b)}},c)}},b={execute:function(){try{var a=document.currentScript&&0==document.currentScript.src.indexOf("http:")?"http:":"https:";var b=h.getMeasurementsScriptUrl(a);k(b)}catch(I){v|=256,e.report(e.ErrorTypes.InjectTagError,I.message,!0)}}},
d="";try{d=H&&document.currentScript.src||F&&F.src}catch(f){}try{var C=function(a){function b(a){var b={};a.split("&").forEach(function(a){a=a.trim().split("=");2===a.length&&(b[a[0].trim()]=a[1].trim())});return b}function c(a){var b={};["cmp","ctx","sid","plc"].forEach(function(c){a.hasOwnProperty(c)&&(b["dvp_"+c]=a[c])});return b}var d={},e={};(function(a){if(a){var f="";a=a.trim().split("?");2===a.length&&(f=a[1]);f&&(d=b(f),e=c(d))}})(a);return{toQueryString:function(a){var b="",c;for(c in a)a.hasOwnProperty(c)&&
(b&&(b+="&"),b=[b,c,"=",a[c]].join(""));return b},getQueryStringParams:function(){return d},getQueryStringClientParams:function(){return e}}}(d);var e=function(){function b(b,d,e){d=(d=d&&d&&d.trim().replace(/(\t|\n|\r|\|)/g,""))&&encodeURIComponent(d)||"";d=c.replace(/__ERR_MSG_PLACEHOLDR__/g,[b.message,d].join("__"));d=d.replace(/__CLIENT_ERROR_TYPE_PLACEHOLDR__/g,b.id);e&&(d+="&dvp_isLostImp=1");a.isSupported()&&(d+="&dvp_iomd=1");p&&(d+="&dvp_csplog="+v);return d}var c="",d={ctx:818052,cmp:1619415,
dvtagver:"6.1.src",tgjsver:"731",napr:"__ERR_MSG_PLACEHOLDR__",cerrt:"__CLIENT_ERROR_TYPE_PLACEHOLDR__"};n&&(d.dvp_idle=1);p&&(d.dvp_csp=1);A||(d.dvp_imrns=1);c=["https://tps.doubleverify.com/visit.jpg?",[C.toQueryString(d),C.toQueryString(C.getQueryStringClientParams())].join("&")].join("");return{ErrorTypes:{InjectTagError:{id:1,message:"InjectTagError"},LoadTagError:{id:2,message:"LoadTagError"},UnexpectedLostImpError:{id:4,message:"UnexpectedLostImpError"},OmidSessionError:{id:8,message:"OmidSessionError"},
OmidUnexpectedLostImpError:{id:16,message:"OmidUnexpectedLostImpError"},OmidLoadTagError:{id:32,message:"OmidLoadTagError"},OmidInjectTagError:{id:64,message:"OmidInjectTagError "},UnexpectedError:{id:128,message:"UnexpectedError"},OmidUnexpectedError:{id:256,message:"OmidUnexpectedError"}},report:function(a,c,d){D(b(a,c,d))},getReportUrl:b}}()}catch(f){r(f,128,0)}try{$dv="undefined"!=typeof $dv&&$dv||{tags:{},tagsCounter:0},$frmId=m(),$dv.tagsCounter++,$dv.sharedUniqueKey=$dv.sharedUniqueKey||m(),
$dv.restrictedAccess=p,u($dv,g,"731",d,p,$frmId),(a.isSupported()?a:b).execute()}catch(f){e?e.report(e.ErrorTypes.UnexpectedLostImpError,f.message,!0):r(f,4,1)}})();
